### PR TITLE
add ni v2 samples

### PR DESCRIPTION
**Pull request by maxkahan**
Adds fraud score and sim swap samples for NI v2

### CODE REVIEW

**Review by superchilled — COMMENTED** [review]
Do we want an snippet with both `fraud_score` and `sim_swap`?

**Comment by maxkahan** [comment]
I'll chase this up internally, we don't currently have a docs page for it

**Review by superchilled — APPROVED** [review]
OK, cool. I'll approve this PR then, and we can always add the other snippet later if necessary in a separate PR.

**Comment by maxkahan** [comment]
@superchilled Have checked and it's fine just to have the two.

**Pull request merged**
